# Generated by Django 4.1.5 on 2023-02-19 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fileupload',
            table='fileupload',
        ),
    ]
