# Generated by Django 4.1.5 on 2023-02-19 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0002_alter_fileupload_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FileUpload',
            new_name='FileUploadModel',
        ),
    ]
